name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: DewendraDinuri
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Colombo
          filename: github-metrics.svg
          plugin_languages: yes
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_followup: yes
          plugin_traffic: yes
          plugin_stargazers: yes
