name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # every day
  push: {branches: ["main"]}
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: DewendraDinuri
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Colombo
          plugin_languages: yes
          plugin_languages.colors: github
          plugin_lines: yes
          plugin_followup: yes
          plugin_traffic: yes
          plugin_isocalendar: yes
          plugin_stargazers: yes
